// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package game

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4086215fDecodeGameserverInternalServicesGameTictactoe(in *jlexer.Lexer, out *TTTMoveData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "move":
			if in.IsNull() {
				in.Skip()
				out.Move = nil
			} else {
				in.Delim('[')
				if out.Move == nil {
					if !in.IsDelim(']') {
						out.Move = make([]int, 0, 8)
					} else {
						out.Move = []int{}
					}
				} else {
					out.Move = (out.Move)[:0]
				}
				for !in.IsDelim(']') {
					var v1 int
					v1 = int(in.Int())
					out.Move = append(out.Move, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4086215fEncodeGameserverInternalServicesGameTictactoe(out *jwriter.Writer, in TTTMoveData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"move\":"
		out.RawString(prefix[1:])
		if in.Move == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Move {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TTTMoveData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4086215fEncodeGameserverInternalServicesGameTictactoe(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TTTMoveData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4086215fEncodeGameserverInternalServicesGameTictactoe(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TTTMoveData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4086215fDecodeGameserverInternalServicesGameTictactoe(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TTTMoveData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4086215fDecodeGameserverInternalServicesGameTictactoe(l, v)
}
func easyjson4086215fDecodeGameserverInternalServicesGameTictactoe1(in *jlexer.Lexer, out *TTTMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "action":
			out.Action = string(in.String())
		case "data":
			out.Data = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4086215fEncodeGameserverInternalServicesGameTictactoe1(out *jwriter.Writer, in TTTMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"action\":"
		out.RawString(prefix[1:])
		out.String(string(in.Action))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TTTMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4086215fEncodeGameserverInternalServicesGameTictactoe1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TTTMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4086215fEncodeGameserverInternalServicesGameTictactoe1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TTTMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4086215fDecodeGameserverInternalServicesGameTictactoe1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TTTMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4086215fDecodeGameserverInternalServicesGameTictactoe1(l, v)
}
