// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package game

import (
	json "encoding/json"

	uuid "github.com/google/uuid"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBd887cf1DecodeGameserverInternalServicesGameTictactoe(in *jlexer.Lexer, out *TTTState) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "field":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v1 := 0
				for !in.IsDelim(']') {
					if v1 < 15 {
						if in.IsNull() {
							in.Skip()
						} else {
							copy((out.Field)[v1][:], in.Bytes())
						}
						v1++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		case "players":
			if in.IsNull() {
				in.Skip()
				out.Players = nil
			} else {
				in.Delim('[')
				if out.Players == nil {
					if !in.IsDelim(']') {
						out.Players = make([]uuid.UUID, 0, 4)
					} else {
						out.Players = []uuid.UUID{}
					}
				} else {
					out.Players = (out.Players)[:0]
				}
				for !in.IsDelim(']') {
					var v3 uuid.UUID
					if data := in.UnsafeBytes(); in.Ok() {
						in.AddError((v3).UnmarshalText(data))
					}
					out.Players = append(out.Players, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "state":
			out.State = string(in.String())
		case "winner":
			out.Winner = int(in.Int())
		case "turn":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.Turn).UnmarshalText(data))
			}
		case "winline":
			if in.IsNull() {
				in.Skip()
				out.WinLine = nil
			} else {
				in.Delim('[')
				if out.WinLine == nil {
					if !in.IsDelim(']') {
						out.WinLine = make([][]int, 0, 2)
					} else {
						out.WinLine = [][]int{}
					}
				} else {
					out.WinLine = (out.WinLine)[:0]
				}
				for !in.IsDelim(']') {
					var v4 []int
					if in.IsNull() {
						in.Skip()
						v4 = nil
					} else {
						in.Delim('[')
						if v4 == nil {
							if !in.IsDelim(']') {
								v4 = make([]int, 0, 8)
							} else {
								v4 = []int{}
							}
						} else {
							v4 = (v4)[:0]
						}
						for !in.IsDelim(']') {
							var v5 int
							v5 = int(in.Int())
							v4 = append(v4, v5)
							in.WantComma()
						}
						in.Delim(']')
					}
					out.WinLine = append(out.WinLine, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "lastmove":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v6 := 0
				for !in.IsDelim(']') {
					if v6 < 2 {
						(out.LastMove)[v6] = int(in.Int())
						v6++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBd887cf1EncodeGameserverInternalServicesGameTictactoe(out *jwriter.Writer, in TTTState) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"field\":"
		out.RawString(prefix[1:])
		out.RawByte('[')
		for v7 := range in.Field {
			if v7 > 0 {
				out.RawByte(',')
			}
			out.Base64Bytes((in.Field)[v7][:])
		}
		out.RawByte(']')
	}
	{
		const prefix string = ",\"players\":"
		out.RawString(prefix)
		if in.Players == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.Players {
				if v9 > 0 {
					out.RawByte(',')
				}
				out.RawText((v10).MarshalText())
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"state\":"
		out.RawString(prefix)
		out.String(string(in.State))
	}
	{
		const prefix string = ",\"winner\":"
		out.RawString(prefix)
		out.Int(int(in.Winner))
	}
	{
		const prefix string = ",\"turn\":"
		out.RawString(prefix)
		out.RawText((in.Turn).MarshalText())
	}
	{
		const prefix string = ",\"winline\":"
		out.RawString(prefix)
		if in.WinLine == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.WinLine {
				if v11 > 0 {
					out.RawByte(',')
				}
				if v12 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v13, v14 := range v12 {
						if v13 > 0 {
							out.RawByte(',')
						}
						out.Int(int(v14))
					}
					out.RawByte(']')
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"lastmove\":"
		out.RawString(prefix)
		out.RawByte('[')
		for v15 := range in.LastMove {
			if v15 > 0 {
				out.RawByte(',')
			}
			out.Int(int((in.LastMove)[v15]))
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TTTState) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBd887cf1EncodeGameserverInternalServicesGameTictactoe(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TTTState) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBd887cf1EncodeGameserverInternalServicesGameTictactoe(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TTTState) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBd887cf1DecodeGameserverInternalServicesGameTictactoe(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TTTState) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBd887cf1DecodeGameserverInternalServicesGameTictactoe(l, v)
}
func easyjsonBd887cf1DecodeGameserverInternalServicesGameTictactoe1(in *jlexer.Lexer, out *TTTSendState) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "field":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v16 := 0
				for !in.IsDelim(']') {
					if v16 < 15 {
						if in.IsNull() {
							in.Skip()
						} else {
							copy((out.Field)[v16][:], in.Bytes())
						}
						v16++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		case "players":
			if in.IsNull() {
				in.Skip()
				out.Players = nil
			} else {
				in.Delim('[')
				if out.Players == nil {
					if !in.IsDelim(']') {
						out.Players = make([]uuid.UUID, 0, 4)
					} else {
						out.Players = []uuid.UUID{}
					}
				} else {
					out.Players = (out.Players)[:0]
				}
				for !in.IsDelim(']') {
					var v18 uuid.UUID
					if data := in.UnsafeBytes(); in.Ok() {
						in.AddError((v18).UnmarshalText(data))
					}
					out.Players = append(out.Players, v18)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "turn":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.Turn).UnmarshalText(data))
			}
		case "you":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.You).UnmarshalText(data))
			}
		case "state":
			out.State = string(in.String())
		case "winner":
			out.Winner = int(in.Int())
		case "winline":
			if in.IsNull() {
				in.Skip()
				out.WinLine = nil
			} else {
				in.Delim('[')
				if out.WinLine == nil {
					if !in.IsDelim(']') {
						out.WinLine = make([][]int, 0, 2)
					} else {
						out.WinLine = [][]int{}
					}
				} else {
					out.WinLine = (out.WinLine)[:0]
				}
				for !in.IsDelim(']') {
					var v19 []int
					if in.IsNull() {
						in.Skip()
						v19 = nil
					} else {
						in.Delim('[')
						if v19 == nil {
							if !in.IsDelim(']') {
								v19 = make([]int, 0, 8)
							} else {
								v19 = []int{}
							}
						} else {
							v19 = (v19)[:0]
						}
						for !in.IsDelim(']') {
							var v20 int
							v20 = int(in.Int())
							v19 = append(v19, v20)
							in.WantComma()
						}
						in.Delim(']')
					}
					out.WinLine = append(out.WinLine, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "lastmove":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v21 := 0
				for !in.IsDelim(']') {
					if v21 < 2 {
						(out.LastMove)[v21] = int(in.Int())
						v21++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBd887cf1EncodeGameserverInternalServicesGameTictactoe1(out *jwriter.Writer, in TTTSendState) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"field\":"
		out.RawString(prefix[1:])
		out.RawByte('[')
		for v22 := range in.Field {
			if v22 > 0 {
				out.RawByte(',')
			}
			out.Base64Bytes((in.Field)[v22][:])
		}
		out.RawByte(']')
	}
	{
		const prefix string = ",\"players\":"
		out.RawString(prefix)
		if in.Players == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v24, v25 := range in.Players {
				if v24 > 0 {
					out.RawByte(',')
				}
				out.RawText((v25).MarshalText())
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"turn\":"
		out.RawString(prefix)
		out.RawText((in.Turn).MarshalText())
	}
	{
		const prefix string = ",\"you\":"
		out.RawString(prefix)
		out.RawText((in.You).MarshalText())
	}
	{
		const prefix string = ",\"state\":"
		out.RawString(prefix)
		out.String(string(in.State))
	}
	{
		const prefix string = ",\"winner\":"
		out.RawString(prefix)
		out.Int(int(in.Winner))
	}
	{
		const prefix string = ",\"winline\":"
		out.RawString(prefix)
		if in.WinLine == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v26, v27 := range in.WinLine {
				if v26 > 0 {
					out.RawByte(',')
				}
				if v27 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v28, v29 := range v27 {
						if v28 > 0 {
							out.RawByte(',')
						}
						out.Int(int(v29))
					}
					out.RawByte(']')
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"lastmove\":"
		out.RawString(prefix)
		out.RawByte('[')
		for v30 := range in.LastMove {
			if v30 > 0 {
				out.RawByte(',')
			}
			out.Int(int((in.LastMove)[v30]))
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TTTSendState) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBd887cf1EncodeGameserverInternalServicesGameTictactoe1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TTTSendState) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBd887cf1EncodeGameserverInternalServicesGameTictactoe1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TTTSendState) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBd887cf1DecodeGameserverInternalServicesGameTictactoe1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TTTSendState) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBd887cf1DecodeGameserverInternalServicesGameTictactoe1(l, v)
}
